### PR TITLE
Map Splash Art

### PR DESCRIPTION
**Pull request by chanson02**
Get rid of some of the "no_texture"s on the map screen.

### CODE REVIEW

**Comment by chanson02** [comment]
@EngineeringDude123 did you find these assets or did you make them? If you made them could you make a few more? We need a bus stop, commons, and dean's office.

**Comment by EngineeringDude123** [comment]
> @EngineeringDude123 did you find these assets or did you make them? If you made them could you make a few more? We need a bus stop, commons, and dean's office.

Yes I can generate more pictures

**Review by EngineeringDude123 — APPROVED** [review]

**Comment by chanson02** [comment]
> Yes I can generate more pictures

Thank you, these ones are 666x360 but if the aspect ratio is a little off I can stretch/shrink it.

**Review by NoahBartell — APPROVED** [review]
LGTM

**Pull request merged**
