### PR TITLE
Installer

### PR DESCRIPTION
**Pull request by chanson02**
Added instructions for creating an executable file for our game.

### CODE REVIEW

**Comment by NoahBartell** [comment]
@chanson02 should we add pyinstaller to the requirements.txt?

**Comment by chanson02** [comment]
I was thinking about it. I decided not to because it's not actually a requirement for the game itself... Interested in what others think.

**Comment by NoahBartell** [comment]
> I was thinking about it. I decided not to because it's not actually a requirement for the game itself... Interested in what others think.

I'm indifferent but I thought I'd mention it

**Review by NoahBartell — APPROVED** [review]
👍

**Review by MLHumphries — APPROVED** [review]

**Review by instMeyFTW — APPROVED** [review]

**Pull request merged**
